apiVersion: v1
kind: Secret
metadata:
  name: vizme-secrets
  namespace: vizme
type: Opaque
data:
  # Postgres
  POSTGRES_DB: "bWV0cmljc19kYg=="
  POSTGRES_USER: "dml6bWU="
  POSTGRES_PASSWORD: "Y2hhbmdlLW1lLXN0cm9uZw=="

  # Backend
  JWT_SECRET: "S0VUUjBOclZhdVlkL29TRjBkeGhocmxUbnowWWNGTGcrS2Vpa2lBUUQ4Y1pOWmhpaXB4VndpbkNOd2paL3FWNQ=="

  # Optional: Prometheus basic_auth for /metrics
  METRICS_SCRAPE_USER: "c2NyYXBl"
  METRICS_SCRAPE_PASSWORD: "Y2hhbmdlLW1lLXN0cm9uZw=="

  # Grafana admin
  GF_SECURITY_ADMIN_USER: "YWRtaW4="
  GF_SECURITY_ADMIN_PASSWORD: "Y2hhbmdlLW1lLXN0cm9uZw=="

  # MinIO (S3 for Mimir)
  MINIO_ROOT_USER: "bWltaXI="
  MINIO_ROOT_PASSWORD: "c3VwZXJzZWNyZXQ="